#!/usr/bin/perl -w

use strict;
use warnings;

use feature qw( switch );
use Term::ANSIColor;
use Cwd;

my $arch = `/bin/uname -m`;
chomp($arch);
print colored("Found ARCH: $arch \n", "bold cyan");

my @utils = qw( htop gkrellmd iptraf-ng screen );

my $cwd = getcwd();
my $mods_dir = "/var/smoothwall/mods";
my $modsa_dir = "/var/smoothwall/mods-available";

given ($cwd) {
	when ('/root/swe-extra-utils') {
		# in dev mode
		print colored("Looks like we're in the dev directory.  Would you like to install this mod to your smoothie?\n", "bold cyan");
		my $ans = readline();
		chomp($ans);
		if ($ans =~ /^[Yy](?:es)?$/) {
			# check for any of the directories
			my $notice_flag = 0;
			foreach my $util ( @utils ) {
				if (-l "$mods_dir/$util") {
					$notice_flag = 1;
					unlink("$mods_dir/$util");
					system("/bin/rm -rf $modsa_dir/$util");
				}
			}
			if ($notice_flag) {
				print colored("Notice:  One or more of the same utilities found in this mod were found to be installed individually.  They have been removed.\n", "bold yellow");
				print colored("Removing these individual mods/utilities is safe and more of a housecleaning measure.\n", "bold yellow");
			}
			print colored("Creating mod directory....\n", "bold cyan");
			system("/bin/mkdir -p $modsa_dir/extra-utils") unless (-d "$modsa_dir/extra-utils");
			print colored("Copying files....\n", "bold cyan");
			system("/bin/cp -rf * $modsa_dir/extra-utils/");
			print colored("Setting up symlinks....\n", "bold cyan");
			chdir("$modsa_dir/extra-utils/bin");
			foreach my $util ( @utils ) { system("/bin/ln -snf $util.$arch $util"); }
			chdir($mods_dir);
			system("/bin/ln -snf ../mods-available/extra-utils extra-utils");
			print colored("To complete setup and use these right now, issue the following command: \n", "bold cyan");
			print colored("\tsource /etc/bashrc\n", "bold green");
			print colored("extra utils are now ready to use with your smoothie.\n", "bold cyan");
		} else {
			print colored("Quitting!\n", "bold red");
		}
	}
	when ("/var/smoothwall/mods-available/extra-utils") {
		print colored("Looks like we're in the dev directory.  Would you like to install this mod to your smoothie?\n", "bold cyan");
		my $ans = readline();
		chomp($ans);
		if ($ans =~ /^[Yy](?:es)?$/) {
			# check for any of the directories
			my $notice_flag = 0;
			foreach my $util ( @utils ) {
				if (-l "$mods_dir/$util") {
					$notice_flag = 1;
					unlink("$mods_dir/$util");
					system("/bin/rm -rf $modsa_dir/$util");
				}
			}
			if ($notice_flag) {
				print colored("Notice:  One or more of the same utilities found in this mod were found to be installed individually.  They have been removed.\n", "bold yellow");
				print colored("Removing these individual mods/utilities is safe and more of a housecleaning measure.\n", "bold yellow");
			}
			print colored("Setting up symlinks....\n", "bold cyan");
			chdir("$modsa_dir/extra-utils/bin");
			foreach my $util ( @utils ) { system("/bin/ln -snf $util.$arch $util"); }
			chdir($mods_dir);
			system("/bin/ln -snf ../mods-available/extra-utils extra-utils");
			print colored("To complete setup and use these right now, issue the following command: \n", "bold cyan");
			print colored("\tsource /etc/bashrc\n", "bold green");
			print colored("extra utils are now ready to use with your smoothie.\n", "bold cyan");
		} else {
			print colored("Quitting!\n", "bold red");
		}
	}
	when ("/tmp/extra-utils") {
		print colored("Looks like we're in the tmp directory.  Would you like to install this mod to your smoothie?\n", "bold cyan");
		my $ans = readline();
		chomp($ans);
		if ($ans =~ /^[Yy](?:es)?$/) {
			# check for any of the directories
			my $notice_flag = 0;
			foreach my $util ( @utils ) {
				if (-l "$mods_dir/$util") {
					$notice_flag = 1;
					unlink("$mods_dir/$util");
					system("/bin/rm -rf $modsa_dir/$util");
				}
			}
			if ($notice_flag) {
				print colored("Notice:  One or more of the same utilities found in this mod were found to be installed individually.  They have been removed.\n", "bold yellow");
				print colored("Removing these individual mods/utilities is safe and more of a housecleaning measure.\n", "bold yellow");
			}
			print colored("Creating mod directory....\n", "bold cyan");
			system("/bin/mkdir -p $modsa_dir/extra-utils") unless (-d "$modsa_dir/extra-utils");
			print colored("Copying files....\n", "bold cyan");
			system("/bin/cp -rf * $modsa_dir/extra-utils/");
			print colored("Setting up symlinks....\n", "bold cyan");
			chdir("$modsa_dir/extra-utils/bin");
			foreach my $util ( @utils ) { system("/bin/ln -snf $util.$arch $util"); }
			chdir($mods_dir);
			system("/bin/ln -snf ../mods-available/extra-utils extra-utils");
			print colored("To complete setup and use these right now, issue the following command: \n", "bold cyan");
			print colored("\tsource /etc/bashrc\n", "bold green");
			print colored("extra utils are now ready to use with your smoothie.\n", "bold cyan");
		} else {
			print colored("Quitting!\n", "bold red");
		}
	}
	when ("$modsa_dir/extra-utils") {
		print colored("Looks like we're in the mods-available directory, so most of the work is already done.  Would you like to install this mod to your smoothie?\n", "bold cyan");
		my $ans = readline();
		chomp($ans);
		if ($ans =~ /^[Yy](?:es)?$/) {
			# check for any of the directories
			my $notice_flag = 0;
			foreach my $util ( @utils ) {
				if (-l "$mods_dir/$util") {
					$notice_flag = 1;
					unlink("$mods_dir/$util");
					system("/bin/rm -rf $modsa_dir/$util");
				}
			}
			if ($notice_flag) {
				print colored("Notice:  One or more of the same utilities found in this mod were found to be installed individually.  They have been removed.\n", "bold yellow");
				print colored("Removing these individual mods/utilities is safe and more of a housecleaning measure.\n", "bold yellow");
			}
			print colored("Creating mod directory....\n", "bold cyan");
			system("/bin/mkdir -p $modsa_dir/extra-utils") unless (-d "$modsa_dir/extra-utils");
			print colored("Copying files....\n", "bold cyan");
			system("/bin/cp -rf * $modsa_dir/extra-utils/");
			print colored("Setting up symlinks....\n", "bold cyan");
			chdir("$modsa_dir/extra-utils/bin");
			foreach my $util ( @utils ) { system("/bin/ln -snf $util.$arch $util"); }
			chdir($mods_dir);
			system("/bin/ln -snf ../mods-available/extra-utils extra-utils");
			print colored("To complete setup and use these right now, issue the following command: \n", "bold cyan");
			print colored("\tsource /etc/bashrc\n", "bold green");
			print colored("extra utils are now ready to use with your smoothie.\n", "bold cyan");
		} else {
			print colored("Quitting!\n", "bold red");
		}
	}
	default { die colored("Unrecognized install path! $cwd \n", "bold red"); exit 1; }
}
